version: '3.8'

services:
  frontend:
    image: mikailozkan/frontend-gasan:latest
    # build:
    #   context: C:/Users/ozkan/Desktop/Develop-ProductProcess-Fr/Develop-ProductProcess-Fr
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8080"
    networks:
      - app-network

  backend:
    image: mikailozkan/backend-gasan:latest
    # build:
    #   context: C:/Users/ozkan/Desktop/GasanApp-Backend/Develop-ProductProcess-Dv
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stajProje
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stajProje
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
